CC=gcc
TARGET = ocpp_driver
CFLAGS = -g -Wall
DEPS = ocpp.h

%.o: %.c $(DEPS)
	$(CC) $< $(CFLAGS) -c -o $@

$(TARGET): ocpp_driver.o ocpp.o 
	$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).o ocpp.o

clean:
	$(RM) $(TARGET) *.o *~
